// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/backend.dart';
import 'api/connection.dart';
import 'api/device_simulator.dart';
import 'api/profile_import.dart';
import 'api/simulator.dart';
import 'api/snapshot.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActivityItem dco_decode_activity_item(dynamic raw);

  @protected
  AppSnapshot dco_decode_app_snapshot(dynamic raw);

  @protected
  BackendStatus dco_decode_backend_status(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  HomeDashboard dco_decode_box_autoadd_home_dashboard(dynamic raw);

  @protected
  ConnectionInfo dco_decode_connection_info(dynamic raw);

  @protected
  DeviceSimulatorExceptionStats dco_decode_device_simulator_exception_stats(
    dynamic raw,
  );

  @protected
  DeviceSimulatorFrame dco_decode_device_simulator_frame(dynamic raw);

  @protected
  DeviceSimulatorRegisterDefinition
  dco_decode_device_simulator_register_definition(dynamic raw);

  @protected
  DeviceSimulatorRegisterState dco_decode_device_simulator_register_state(
    dynamic raw,
  );

  @protected
  DeviceSimulatorStatus dco_decode_device_simulator_status(dynamic raw);

  @protected
  DeviceSimulatorValueUpdate dco_decode_device_simulator_value_update(
    dynamic raw,
  );

  @protected
  DeviceStatus dco_decode_device_status(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FaultConfig dco_decode_fault_config(dynamic raw);

  @protected
  HomeConnectionStatus dco_decode_home_connection_status(dynamic raw);

  @protected
  HomeDashboard dco_decode_home_dashboard(dynamic raw);

  @protected
  HomeDashboardValue dco_decode_home_dashboard_value(dynamic raw);

  @protected
  ImportedSimulatorProfile dco_decode_imported_simulator_profile(dynamic raw);

  @protected
  ImportedSimulatorRegister dco_decode_imported_simulator_register(dynamic raw);

  @protected
  ImportedSimulatorScenario dco_decode_imported_simulator_scenario(dynamic raw);

  @protected
  ImportedSimulatorScenarioStep dco_decode_imported_simulator_scenario_step(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ActivityItem> dco_decode_list_activity_item(dynamic raw);

  @protected
  List<DeviceSimulatorFrame> dco_decode_list_device_simulator_frame(
    dynamic raw,
  );

  @protected
  List<DeviceSimulatorRegisterDefinition>
  dco_decode_list_device_simulator_register_definition(dynamic raw);

  @protected
  List<DeviceSimulatorRegisterState>
  dco_decode_list_device_simulator_register_state(dynamic raw);

  @protected
  List<DeviceSimulatorValueUpdate>
  dco_decode_list_device_simulator_value_update(dynamic raw);

  @protected
  List<DeviceStatus> dco_decode_list_device_status(dynamic raw);

  @protected
  List<HomeDashboardValue> dco_decode_list_home_dashboard_value(dynamic raw);

  @protected
  List<ImportedSimulatorRegister> dco_decode_list_imported_simulator_register(
    dynamic raw,
  );

  @protected
  List<ImportedSimulatorScenario> dco_decode_list_imported_simulator_scenario(
    dynamic raw,
  );

  @protected
  List<ImportedSimulatorScenarioStep>
  dco_decode_list_imported_simulator_scenario_step(dynamic raw);

  @protected
  List<MetricCard> dco_decode_list_metric_card(dynamic raw);

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TrendPoint> dco_decode_list_trend_point(dynamic raw);

  @protected
  MetricCard dco_decode_metric_card(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  HomeDashboard? dco_decode_opt_box_autoadd_home_dashboard(dynamic raw);

  @protected
  ProjectInfo dco_decode_project_info(dynamic raw);

  @protected
  SimulatorStatus dco_decode_simulator_status(dynamic raw);

  @protected
  TrendPoint dco_decode_trend_point(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActivityItem sse_decode_activity_item(SseDeserializer deserializer);

  @protected
  AppSnapshot sse_decode_app_snapshot(SseDeserializer deserializer);

  @protected
  BackendStatus sse_decode_backend_status(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HomeDashboard sse_decode_box_autoadd_home_dashboard(
    SseDeserializer deserializer,
  );

  @protected
  ConnectionInfo sse_decode_connection_info(SseDeserializer deserializer);

  @protected
  DeviceSimulatorExceptionStats sse_decode_device_simulator_exception_stats(
    SseDeserializer deserializer,
  );

  @protected
  DeviceSimulatorFrame sse_decode_device_simulator_frame(
    SseDeserializer deserializer,
  );

  @protected
  DeviceSimulatorRegisterDefinition
  sse_decode_device_simulator_register_definition(SseDeserializer deserializer);

  @protected
  DeviceSimulatorRegisterState sse_decode_device_simulator_register_state(
    SseDeserializer deserializer,
  );

  @protected
  DeviceSimulatorStatus sse_decode_device_simulator_status(
    SseDeserializer deserializer,
  );

  @protected
  DeviceSimulatorValueUpdate sse_decode_device_simulator_value_update(
    SseDeserializer deserializer,
  );

  @protected
  DeviceStatus sse_decode_device_status(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FaultConfig sse_decode_fault_config(SseDeserializer deserializer);

  @protected
  HomeConnectionStatus sse_decode_home_connection_status(
    SseDeserializer deserializer,
  );

  @protected
  HomeDashboard sse_decode_home_dashboard(SseDeserializer deserializer);

  @protected
  HomeDashboardValue sse_decode_home_dashboard_value(
    SseDeserializer deserializer,
  );

  @protected
  ImportedSimulatorProfile sse_decode_imported_simulator_profile(
    SseDeserializer deserializer,
  );

  @protected
  ImportedSimulatorRegister sse_decode_imported_simulator_register(
    SseDeserializer deserializer,
  );

  @protected
  ImportedSimulatorScenario sse_decode_imported_simulator_scenario(
    SseDeserializer deserializer,
  );

  @protected
  ImportedSimulatorScenarioStep sse_decode_imported_simulator_scenario_step(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ActivityItem> sse_decode_list_activity_item(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceSimulatorFrame> sse_decode_list_device_simulator_frame(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceSimulatorRegisterDefinition>
  sse_decode_list_device_simulator_register_definition(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceSimulatorRegisterState>
  sse_decode_list_device_simulator_register_state(SseDeserializer deserializer);

  @protected
  List<DeviceSimulatorValueUpdate>
  sse_decode_list_device_simulator_value_update(SseDeserializer deserializer);

  @protected
  List<DeviceStatus> sse_decode_list_device_status(
    SseDeserializer deserializer,
  );

  @protected
  List<HomeDashboardValue> sse_decode_list_home_dashboard_value(
    SseDeserializer deserializer,
  );

  @protected
  List<ImportedSimulatorRegister> sse_decode_list_imported_simulator_register(
    SseDeserializer deserializer,
  );

  @protected
  List<ImportedSimulatorScenario> sse_decode_list_imported_simulator_scenario(
    SseDeserializer deserializer,
  );

  @protected
  List<ImportedSimulatorScenarioStep>
  sse_decode_list_imported_simulator_scenario_step(
    SseDeserializer deserializer,
  );

  @protected
  List<MetricCard> sse_decode_list_metric_card(SseDeserializer deserializer);

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TrendPoint> sse_decode_list_trend_point(SseDeserializer deserializer);

  @protected
  MetricCard sse_decode_metric_card(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HomeDashboard? sse_decode_opt_box_autoadd_home_dashboard(
    SseDeserializer deserializer,
  );

  @protected
  ProjectInfo sse_decode_project_info(SseDeserializer deserializer);

  @protected
  SimulatorStatus sse_decode_simulator_status(SseDeserializer deserializer);

  @protected
  TrendPoint sse_decode_trend_point(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_activity_item(ActivityItem self, SseSerializer serializer);

  @protected
  void sse_encode_app_snapshot(AppSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_backend_status(BackendStatus self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_home_dashboard(
    HomeDashboard self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_info(
    ConnectionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_simulator_exception_stats(
    DeviceSimulatorExceptionStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_simulator_frame(
    DeviceSimulatorFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_simulator_register_definition(
    DeviceSimulatorRegisterDefinition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_simulator_register_state(
    DeviceSimulatorRegisterState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_simulator_status(
    DeviceSimulatorStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_simulator_value_update(
    DeviceSimulatorValueUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_status(DeviceStatus self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fault_config(FaultConfig self, SseSerializer serializer);

  @protected
  void sse_encode_home_connection_status(
    HomeConnectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_home_dashboard(HomeDashboard self, SseSerializer serializer);

  @protected
  void sse_encode_home_dashboard_value(
    HomeDashboardValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_imported_simulator_profile(
    ImportedSimulatorProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_imported_simulator_register(
    ImportedSimulatorRegister self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_imported_simulator_scenario(
    ImportedSimulatorScenario self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_imported_simulator_scenario_step(
    ImportedSimulatorScenarioStep self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_activity_item(
    List<ActivityItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_simulator_frame(
    List<DeviceSimulatorFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_simulator_register_definition(
    List<DeviceSimulatorRegisterDefinition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_simulator_register_state(
    List<DeviceSimulatorRegisterState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_simulator_value_update(
    List<DeviceSimulatorValueUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_status(
    List<DeviceStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_home_dashboard_value(
    List<HomeDashboardValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_imported_simulator_register(
    List<ImportedSimulatorRegister> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_imported_simulator_scenario(
    List<ImportedSimulatorScenario> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_imported_simulator_scenario_step(
    List<ImportedSimulatorScenarioStep> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_metric_card(
    List<MetricCard> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trend_point(
    List<TrendPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metric_card(MetricCard self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_home_dashboard(
    HomeDashboard? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_info(ProjectInfo self, SseSerializer serializer);

  @protected
  void sse_encode_simulator_status(
    SimulatorStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_trend_point(TrendPoint self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
