// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/backend.dart';
import 'api/connection.dart';
import 'api/device_simulator.dart';
import 'api/profile_import.dart';
import 'api/simulator.dart';
import 'api/snapshot.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiBackendInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1463578513;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'icstudio_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  DeviceSimulatorStatus crateApiDeviceSimulatorApplyDeviceSimulatorValues({
    required List<DeviceSimulatorValueUpdate> updates,
  });

  Future<HomeConnectionStatus> crateApiConnectionConnectHomeModbus({
    required String host,
    required int port,
    required int unitId,
  });

  Future<DeviceSimulatorExceptionStats>
  crateApiDeviceSimulatorDeviceSimulatorExceptionStatsDefault();

  HomeConnectionStatus crateApiConnectionDisconnectHomeModbus();

  Future<FaultConfig> crateApiDeviceSimulatorFaultConfigDefault();

  AppSnapshot crateApiSnapshotGetAppSnapshot();

  BackendStatus crateApiBackendGetBackendStatus();

  DeviceSimulatorStatus crateApiDeviceSimulatorGetDeviceSimulatorStatus();

  HomeConnectionStatus crateApiConnectionGetHomeConnectionStatus();

  HomeDashboard crateApiConnectionGetHomeDashboard();

  SimulatorStatus crateApiSimulatorGetHomeSelfTestStatus();

  Future<ImportedSimulatorProfile>
  crateApiProfileImportImportDeviceSimulatorProfile({required String path});

  Future<void> crateApiBackendInitApp();

  Future<HomeConnectionStatus> crateApiConnectionRefreshHomeModbus();

  DeviceSimulatorStatus crateApiDeviceSimulatorSetDeviceSimulatorFault({
    required String mode,
    required int exceptionCode,
    required double rate,
  });

  DeviceSimulatorStatus crateApiDeviceSimulatorSetDeviceSimulatorRegister({
    required int address,
    required double engineeringValue,
  });

  SimulatorStatus crateApiSimulatorSetHomeSelfTestRegister({
    required int address,
    required int rawValue,
  });

  Future<DeviceSimulatorStatus> crateApiDeviceSimulatorStartDeviceSimulator({
    required String host,
    required int port,
    required int unitId,
    required List<DeviceSimulatorRegisterDefinition> registers,
  });

  Future<HomeConnectionStatus> crateApiSimulatorStartHomeSelfTest({
    required String host,
    required int port,
    required int unitId,
  });

  DeviceSimulatorStatus crateApiDeviceSimulatorStopDeviceSimulator();

  SimulatorStatus crateApiSimulatorStopHomeSelfTest();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  DeviceSimulatorStatus crateApiDeviceSimulatorApplyDeviceSimulatorValues({
    required List<DeviceSimulatorValueUpdate> updates,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_device_simulator_value_update(updates, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_simulator_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeviceSimulatorApplyDeviceSimulatorValuesConstMeta,
        argValues: [updates],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDeviceSimulatorApplyDeviceSimulatorValuesConstMeta =>
      const TaskConstMeta(
        debugName: "apply_device_simulator_values",
        argNames: ["updates"],
      );

  @override
  Future<HomeConnectionStatus> crateApiConnectionConnectHomeModbus({
    required String host,
    required int port,
    required int unitId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_u_8(unitId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_connection_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionConnectHomeModbusConstMeta,
        argValues: [host, port, unitId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectHomeModbusConstMeta =>
      const TaskConstMeta(
        debugName: "connect_home_modbus",
        argNames: ["host", "port", "unitId"],
      );

  @override
  Future<DeviceSimulatorExceptionStats>
  crateApiDeviceSimulatorDeviceSimulatorExceptionStatsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_simulator_exception_stats,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiDeviceSimulatorDeviceSimulatorExceptionStatsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDeviceSimulatorDeviceSimulatorExceptionStatsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "device_simulator_exception_stats_default",
        argNames: [],
      );

  @override
  HomeConnectionStatus crateApiConnectionDisconnectHomeModbus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_connection_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionDisconnectHomeModbusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionDisconnectHomeModbusConstMeta =>
      const TaskConstMeta(debugName: "disconnect_home_modbus", argNames: []);

  @override
  Future<FaultConfig> crateApiDeviceSimulatorFaultConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_fault_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeviceSimulatorFaultConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceSimulatorFaultConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "fault_config_default", argNames: []);

  @override
  AppSnapshot crateApiSnapshotGetAppSnapshot() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSnapshotGetAppSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnapshotGetAppSnapshotConstMeta =>
      const TaskConstMeta(debugName: "get_app_snapshot", argNames: []);

  @override
  BackendStatus crateApiBackendGetBackendStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_backend_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBackendGetBackendStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBackendGetBackendStatusConstMeta =>
      const TaskConstMeta(debugName: "get_backend_status", argNames: []);

  @override
  DeviceSimulatorStatus crateApiDeviceSimulatorGetDeviceSimulatorStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_simulator_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeviceSimulatorGetDeviceSimulatorStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceSimulatorGetDeviceSimulatorStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_device_simulator_status",
        argNames: [],
      );

  @override
  HomeConnectionStatus crateApiConnectionGetHomeConnectionStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_connection_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionGetHomeConnectionStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionGetHomeConnectionStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_home_connection_status",
        argNames: [],
      );

  @override
  HomeDashboard crateApiConnectionGetHomeDashboard() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_dashboard,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionGetHomeDashboardConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionGetHomeDashboardConstMeta =>
      const TaskConstMeta(debugName: "get_home_dashboard", argNames: []);

  @override
  SimulatorStatus crateApiSimulatorGetHomeSelfTestStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_simulator_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimulatorGetHomeSelfTestStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimulatorGetHomeSelfTestStatusConstMeta =>
      const TaskConstMeta(debugName: "get_home_self_test_status", argNames: []);

  @override
  Future<ImportedSimulatorProfile>
  crateApiProfileImportImportDeviceSimulatorProfile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_imported_simulator_profile,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProfileImportImportDeviceSimulatorProfileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiProfileImportImportDeviceSimulatorProfileConstMeta =>
      const TaskConstMeta(
        debugName: "import_device_simulator_profile",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiBackendInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBackendInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBackendInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<HomeConnectionStatus> crateApiConnectionRefreshHomeModbus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_connection_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionRefreshHomeModbusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionRefreshHomeModbusConstMeta =>
      const TaskConstMeta(debugName: "refresh_home_modbus", argNames: []);

  @override
  DeviceSimulatorStatus crateApiDeviceSimulatorSetDeviceSimulatorFault({
    required String mode,
    required int exceptionCode,
    required double rate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mode, serializer);
          sse_encode_u_8(exceptionCode, serializer);
          sse_encode_f_64(rate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_simulator_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeviceSimulatorSetDeviceSimulatorFaultConstMeta,
        argValues: [mode, exceptionCode, rate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceSimulatorSetDeviceSimulatorFaultConstMeta =>
      const TaskConstMeta(
        debugName: "set_device_simulator_fault",
        argNames: ["mode", "exceptionCode", "rate"],
      );

  @override
  DeviceSimulatorStatus crateApiDeviceSimulatorSetDeviceSimulatorRegister({
    required int address,
    required double engineeringValue,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(address, serializer);
          sse_encode_f_64(engineeringValue, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_simulator_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeviceSimulatorSetDeviceSimulatorRegisterConstMeta,
        argValues: [address, engineeringValue],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDeviceSimulatorSetDeviceSimulatorRegisterConstMeta =>
      const TaskConstMeta(
        debugName: "set_device_simulator_register",
        argNames: ["address", "engineeringValue"],
      );

  @override
  SimulatorStatus crateApiSimulatorSetHomeSelfTestRegister({
    required int address,
    required int rawValue,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(address, serializer);
          sse_encode_u_16(rawValue, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_simulator_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimulatorSetHomeSelfTestRegisterConstMeta,
        argValues: [address, rawValue],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimulatorSetHomeSelfTestRegisterConstMeta =>
      const TaskConstMeta(
        debugName: "set_home_self_test_register",
        argNames: ["address", "rawValue"],
      );

  @override
  Future<DeviceSimulatorStatus> crateApiDeviceSimulatorStartDeviceSimulator({
    required String host,
    required int port,
    required int unitId,
    required List<DeviceSimulatorRegisterDefinition> registers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_u_8(unitId, serializer);
          sse_encode_list_device_simulator_register_definition(
            registers,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_simulator_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeviceSimulatorStartDeviceSimulatorConstMeta,
        argValues: [host, port, unitId, registers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceSimulatorStartDeviceSimulatorConstMeta =>
      const TaskConstMeta(
        debugName: "start_device_simulator",
        argNames: ["host", "port", "unitId", "registers"],
      );

  @override
  Future<HomeConnectionStatus> crateApiSimulatorStartHomeSelfTest({
    required String host,
    required int port,
    required int unitId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_u_8(unitId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_connection_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimulatorStartHomeSelfTestConstMeta,
        argValues: [host, port, unitId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimulatorStartHomeSelfTestConstMeta =>
      const TaskConstMeta(
        debugName: "start_home_self_test",
        argNames: ["host", "port", "unitId"],
      );

  @override
  DeviceSimulatorStatus crateApiDeviceSimulatorStopDeviceSimulator() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_simulator_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeviceSimulatorStopDeviceSimulatorConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceSimulatorStopDeviceSimulatorConstMeta =>
      const TaskConstMeta(debugName: "stop_device_simulator", argNames: []);

  @override
  SimulatorStatus crateApiSimulatorStopHomeSelfTest() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_simulator_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimulatorStopHomeSelfTestConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimulatorStopHomeSelfTestConstMeta =>
      const TaskConstMeta(debugName: "stop_home_self_test", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActivityItem dco_decode_activity_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ActivityItem(
      tone: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      detail: dco_decode_String(arr[2]),
      time: dco_decode_String(arr[3]),
    );
  }

  @protected
  AppSnapshot dco_decode_app_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AppSnapshot(
      project: dco_decode_project_info(arr[0]),
      connection: dco_decode_connection_info(arr[1]),
      metrics: dco_decode_list_metric_card(arr[2]),
      devices: dco_decode_list_device_status(arr[3]),
      activities: dco_decode_list_activity_item(arr[4]),
      trends: dco_decode_list_trend_point(arr[5]),
      homeDashboard: dco_decode_opt_box_autoadd_home_dashboard(arr[6]),
    );
  }

  @protected
  BackendStatus dco_decode_backend_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BackendStatus(
      serviceName: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      bridgeReady: dco_decode_bool(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HomeDashboard dco_decode_box_autoadd_home_dashboard(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_home_dashboard(raw);
  }

  @protected
  ConnectionInfo dco_decode_connection_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ConnectionInfo(
      mode: dco_decode_String(arr[0]),
      endpoint: dco_decode_String(arr[1]),
      status: dco_decode_String(arr[2]),
      latencyMs: dco_decode_u_16(arr[3]),
      successRate: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  DeviceSimulatorExceptionStats dco_decode_device_simulator_exception_stats(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DeviceSimulatorExceptionStats(
      ok: dco_decode_u_32(arr[0]),
      exceptionCode: dco_decode_u_32(arr[1]),
      timeout: dco_decode_u_32(arr[2]),
      noResponse: dco_decode_u_32(arr[3]),
      outOfRange: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  DeviceSimulatorFrame dco_decode_device_simulator_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DeviceSimulatorFrame(
      direction: dco_decode_String(arr[0]),
      time: dco_decode_String(arr[1]),
      frame: dco_decode_String(arr[2]),
      note: dco_decode_String(arr[3]),
    );
  }

  @protected
  DeviceSimulatorRegisterDefinition
  dco_decode_device_simulator_register_definition(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DeviceSimulatorRegisterDefinition(
      address: dco_decode_u_16(arr[0]),
      name: dco_decode_String(arr[1]),
      dataType: dco_decode_String(arr[2]),
      length: dco_decode_u_16(arr[3]),
      scale: dco_decode_f_64(arr[4]),
      unit: dco_decode_String(arr[5]),
      engineeringValue: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  DeviceSimulatorRegisterState dco_decode_device_simulator_register_state(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return DeviceSimulatorRegisterState(
      address: dco_decode_u_16(arr[0]),
      name: dco_decode_String(arr[1]),
      dataType: dco_decode_String(arr[2]),
      length: dco_decode_u_16(arr[3]),
      scale: dco_decode_f_64(arr[4]),
      unit: dco_decode_String(arr[5]),
      engineeringValue: dco_decode_f_64(arr[6]),
      rawWords: dco_decode_list_prim_u_16_strict(arr[7]),
    );
  }

  @protected
  DeviceSimulatorStatus dco_decode_device_simulator_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return DeviceSimulatorStatus(
      running: dco_decode_bool(arr[0]),
      endpoint: dco_decode_String(arr[1]),
      unitId: dco_decode_u_8(arr[2]),
      faultMode: dco_decode_String(arr[3]),
      registers: dco_decode_list_device_simulator_register_state(arr[4]),
      logs: dco_decode_list_String(arr[5]),
      frames: dco_decode_list_device_simulator_frame(arr[6]),
      stats: dco_decode_device_simulator_exception_stats(arr[7]),
    );
  }

  @protected
  DeviceSimulatorValueUpdate dco_decode_device_simulator_value_update(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DeviceSimulatorValueUpdate(
      address: dco_decode_u_16(arr[0]),
      engineeringValue: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  DeviceStatus dco_decode_device_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DeviceStatus(
      name: dco_decode_String(arr[0]),
      deviceType: dco_decode_String(arr[1]),
      connection: dco_decode_String(arr[2]),
      runtime: dco_decode_String(arr[3]),
      quality: dco_decode_String(arr[4]),
      lastSeen: dco_decode_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FaultConfig dco_decode_fault_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FaultConfig(
      mode: dco_decode_String(arr[0]),
      exceptionCode: dco_decode_u_8(arr[1]),
      rate: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  HomeConnectionStatus dco_decode_home_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return HomeConnectionStatus(
      connected: dco_decode_bool(arr[0]),
      endpoint: dco_decode_String(arr[1]),
      unitId: dco_decode_u_8(arr[2]),
      status: dco_decode_String(arr[3]),
      latencyMs: dco_decode_u_32(arr[4]),
      successRate: dco_decode_f_64(arr[5]),
      lastReadAddress: dco_decode_u_16(arr[6]),
      lastReadValue: dco_decode_u_16(arr[7]),
      message: dco_decode_String(arr[8]),
    );
  }

  @protected
  HomeDashboard dco_decode_home_dashboard(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HomeDashboard(
      endpoint: dco_decode_String(arr[0]),
      connectionStatus: dco_decode_String(arr[1]),
      values: dco_decode_list_home_dashboard_value(arr[2]),
      lastUpdated: dco_decode_String(arr[3]),
    );
  }

  @protected
  HomeDashboardValue dco_decode_home_dashboard_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return HomeDashboardValue(
      address: dco_decode_u_16(arr[0]),
      name: dco_decode_String(arr[1]),
      rawValue: dco_decode_u_16(arr[2]),
      engineeringValue: dco_decode_f_64(arr[3]),
      displayValue: dco_decode_String(arr[4]),
      unit: dco_decode_String(arr[5]),
      quality: dco_decode_String(arr[6]),
    );
  }

  @protected
  ImportedSimulatorProfile dco_decode_imported_simulator_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ImportedSimulatorProfile(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      version: dco_decode_String(arr[2]),
      deviceType: dco_decode_String(arr[3]),
      vendor: dco_decode_String(arr[4]),
      communicationType: dco_decode_String(arr[5]),
      registers: dco_decode_list_imported_simulator_register(arr[6]),
      scenarios: dco_decode_list_imported_simulator_scenario(arr[7]),
    );
  }

  @protected
  ImportedSimulatorRegister dco_decode_imported_simulator_register(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return ImportedSimulatorRegister(
      id: dco_decode_String(arr[0]),
      address: dco_decode_u_16(arr[1]),
      name: dco_decode_String(arr[2]),
      functionCode: dco_decode_u_8(arr[3]),
      access: dco_decode_String(arr[4]),
      dataType: dco_decode_String(arr[5]),
      length: dco_decode_u_16(arr[6]),
      scale: dco_decode_f_64(arr[7]),
      unit: dco_decode_String(arr[8]),
      rangeMin: dco_decode_opt_box_autoadd_f_64(arr[9]),
      rangeMax: dco_decode_opt_box_autoadd_f_64(arr[10]),
      description: dco_decode_String(arr[11]),
      group: dco_decode_String(arr[12]),
      engineeringValue: dco_decode_f_64(arr[13]),
    );
  }

  @protected
  ImportedSimulatorScenario dco_decode_imported_simulator_scenario(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ImportedSimulatorScenario(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      steps: dco_decode_list_imported_simulator_scenario_step(arr[3]),
      faultMode: dco_decode_String(arr[4]),
      exceptionCode: dco_decode_u_8(arr[5]),
      rate: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  ImportedSimulatorScenarioStep dco_decode_imported_simulator_scenario_step(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ImportedSimulatorScenarioStep(
      registerId: dco_decode_String(arr[0]),
      strategy: dco_decode_String(arr[1]),
      value: dco_decode_opt_box_autoadd_f_64(arr[2]),
      min: dco_decode_opt_box_autoadd_f_64(arr[3]),
      max: dco_decode_opt_box_autoadd_f_64(arr[4]),
      step: dco_decode_opt_box_autoadd_f_64(arr[5]),
      amplitude: dco_decode_opt_box_autoadd_f_64(arr[6]),
      offset: dco_decode_opt_box_autoadd_f_64(arr[7]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ActivityItem> dco_decode_list_activity_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_activity_item).toList();
  }

  @protected
  List<DeviceSimulatorFrame> dco_decode_list_device_simulator_frame(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_device_simulator_frame)
        .toList();
  }

  @protected
  List<DeviceSimulatorRegisterDefinition>
  dco_decode_list_device_simulator_register_definition(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_device_simulator_register_definition)
        .toList();
  }

  @protected
  List<DeviceSimulatorRegisterState>
  dco_decode_list_device_simulator_register_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_device_simulator_register_state)
        .toList();
  }

  @protected
  List<DeviceSimulatorValueUpdate>
  dco_decode_list_device_simulator_value_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_device_simulator_value_update)
        .toList();
  }

  @protected
  List<DeviceStatus> dco_decode_list_device_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_device_status).toList();
  }

  @protected
  List<HomeDashboardValue> dco_decode_list_home_dashboard_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_home_dashboard_value).toList();
  }

  @protected
  List<ImportedSimulatorRegister> dco_decode_list_imported_simulator_register(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_imported_simulator_register)
        .toList();
  }

  @protected
  List<ImportedSimulatorScenario> dco_decode_list_imported_simulator_scenario(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_imported_simulator_scenario)
        .toList();
  }

  @protected
  List<ImportedSimulatorScenarioStep>
  dco_decode_list_imported_simulator_scenario_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_imported_simulator_scenario_step)
        .toList();
  }

  @protected
  List<MetricCard> dco_decode_list_metric_card(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_metric_card).toList();
  }

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TrendPoint> dco_decode_list_trend_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_trend_point).toList();
  }

  @protected
  MetricCard dco_decode_metric_card(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MetricCard(
      key: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      value: dco_decode_String(arr[2]),
      unit: dco_decode_String(arr[3]),
      tone: dco_decode_String(arr[4]),
      helper: dco_decode_String(arr[5]),
    );
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  HomeDashboard? dco_decode_opt_box_autoadd_home_dashboard(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_home_dashboard(raw);
  }

  @protected
  ProjectInfo dco_decode_project_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProjectInfo(
      name: dco_decode_String(arr[0]),
      protocolVersion: dco_decode_String(arr[1]),
      operator_: dco_decode_String(arr[2]),
    );
  }

  @protected
  SimulatorStatus dco_decode_simulator_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SimulatorStatus(
      running: dco_decode_bool(arr[0]),
      endpoint: dco_decode_String(arr[1]),
      unitId: dco_decode_u_8(arr[2]),
      registerCount: dco_decode_u_32(arr[3]),
      logs: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  TrendPoint dco_decode_trend_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TrendPoint(
      time: dco_decode_String(arr[0]),
      power: dco_decode_f_64(arr[1]),
      soc: dco_decode_f_64(arr[2]),
      quality: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActivityItem sse_decode_activity_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tone = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    var var_time = sse_decode_String(deserializer);
    return ActivityItem(
      tone: var_tone,
      title: var_title,
      detail: var_detail,
      time: var_time,
    );
  }

  @protected
  AppSnapshot sse_decode_app_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_project = sse_decode_project_info(deserializer);
    var var_connection = sse_decode_connection_info(deserializer);
    var var_metrics = sse_decode_list_metric_card(deserializer);
    var var_devices = sse_decode_list_device_status(deserializer);
    var var_activities = sse_decode_list_activity_item(deserializer);
    var var_trends = sse_decode_list_trend_point(deserializer);
    var var_homeDashboard = sse_decode_opt_box_autoadd_home_dashboard(
      deserializer,
    );
    return AppSnapshot(
      project: var_project,
      connection: var_connection,
      metrics: var_metrics,
      devices: var_devices,
      activities: var_activities,
      trends: var_trends,
      homeDashboard: var_homeDashboard,
    );
  }

  @protected
  BackendStatus sse_decode_backend_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serviceName = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_bridgeReady = sse_decode_bool(deserializer);
    return BackendStatus(
      serviceName: var_serviceName,
      version: var_version,
      bridgeReady: var_bridgeReady,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  HomeDashboard sse_decode_box_autoadd_home_dashboard(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_home_dashboard(deserializer));
  }

  @protected
  ConnectionInfo sse_decode_connection_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mode = sse_decode_String(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_latencyMs = sse_decode_u_16(deserializer);
    var var_successRate = sse_decode_f_64(deserializer);
    return ConnectionInfo(
      mode: var_mode,
      endpoint: var_endpoint,
      status: var_status,
      latencyMs: var_latencyMs,
      successRate: var_successRate,
    );
  }

  @protected
  DeviceSimulatorExceptionStats sse_decode_device_simulator_exception_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_u_32(deserializer);
    var var_exceptionCode = sse_decode_u_32(deserializer);
    var var_timeout = sse_decode_u_32(deserializer);
    var var_noResponse = sse_decode_u_32(deserializer);
    var var_outOfRange = sse_decode_u_32(deserializer);
    return DeviceSimulatorExceptionStats(
      ok: var_ok,
      exceptionCode: var_exceptionCode,
      timeout: var_timeout,
      noResponse: var_noResponse,
      outOfRange: var_outOfRange,
    );
  }

  @protected
  DeviceSimulatorFrame sse_decode_device_simulator_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_direction = sse_decode_String(deserializer);
    var var_time = sse_decode_String(deserializer);
    var var_frame = sse_decode_String(deserializer);
    var var_note = sse_decode_String(deserializer);
    return DeviceSimulatorFrame(
      direction: var_direction,
      time: var_time,
      frame: var_frame,
      note: var_note,
    );
  }

  @protected
  DeviceSimulatorRegisterDefinition
  sse_decode_device_simulator_register_definition(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_u_16(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_dataType = sse_decode_String(deserializer);
    var var_length = sse_decode_u_16(deserializer);
    var var_scale = sse_decode_f_64(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_engineeringValue = sse_decode_f_64(deserializer);
    return DeviceSimulatorRegisterDefinition(
      address: var_address,
      name: var_name,
      dataType: var_dataType,
      length: var_length,
      scale: var_scale,
      unit: var_unit,
      engineeringValue: var_engineeringValue,
    );
  }

  @protected
  DeviceSimulatorRegisterState sse_decode_device_simulator_register_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_u_16(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_dataType = sse_decode_String(deserializer);
    var var_length = sse_decode_u_16(deserializer);
    var var_scale = sse_decode_f_64(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_engineeringValue = sse_decode_f_64(deserializer);
    var var_rawWords = sse_decode_list_prim_u_16_strict(deserializer);
    return DeviceSimulatorRegisterState(
      address: var_address,
      name: var_name,
      dataType: var_dataType,
      length: var_length,
      scale: var_scale,
      unit: var_unit,
      engineeringValue: var_engineeringValue,
      rawWords: var_rawWords,
    );
  }

  @protected
  DeviceSimulatorStatus sse_decode_device_simulator_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_running = sse_decode_bool(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_unitId = sse_decode_u_8(deserializer);
    var var_faultMode = sse_decode_String(deserializer);
    var var_registers = sse_decode_list_device_simulator_register_state(
      deserializer,
    );
    var var_logs = sse_decode_list_String(deserializer);
    var var_frames = sse_decode_list_device_simulator_frame(deserializer);
    var var_stats = sse_decode_device_simulator_exception_stats(deserializer);
    return DeviceSimulatorStatus(
      running: var_running,
      endpoint: var_endpoint,
      unitId: var_unitId,
      faultMode: var_faultMode,
      registers: var_registers,
      logs: var_logs,
      frames: var_frames,
      stats: var_stats,
    );
  }

  @protected
  DeviceSimulatorValueUpdate sse_decode_device_simulator_value_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_u_16(deserializer);
    var var_engineeringValue = sse_decode_f_64(deserializer);
    return DeviceSimulatorValueUpdate(
      address: var_address,
      engineeringValue: var_engineeringValue,
    );
  }

  @protected
  DeviceStatus sse_decode_device_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_connection = sse_decode_String(deserializer);
    var var_runtime = sse_decode_String(deserializer);
    var var_quality = sse_decode_String(deserializer);
    var var_lastSeen = sse_decode_String(deserializer);
    return DeviceStatus(
      name: var_name,
      deviceType: var_deviceType,
      connection: var_connection,
      runtime: var_runtime,
      quality: var_quality,
      lastSeen: var_lastSeen,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FaultConfig sse_decode_fault_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mode = sse_decode_String(deserializer);
    var var_exceptionCode = sse_decode_u_8(deserializer);
    var var_rate = sse_decode_f_64(deserializer);
    return FaultConfig(
      mode: var_mode,
      exceptionCode: var_exceptionCode,
      rate: var_rate,
    );
  }

  @protected
  HomeConnectionStatus sse_decode_home_connection_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_connected = sse_decode_bool(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_unitId = sse_decode_u_8(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_latencyMs = sse_decode_u_32(deserializer);
    var var_successRate = sse_decode_f_64(deserializer);
    var var_lastReadAddress = sse_decode_u_16(deserializer);
    var var_lastReadValue = sse_decode_u_16(deserializer);
    var var_message = sse_decode_String(deserializer);
    return HomeConnectionStatus(
      connected: var_connected,
      endpoint: var_endpoint,
      unitId: var_unitId,
      status: var_status,
      latencyMs: var_latencyMs,
      successRate: var_successRate,
      lastReadAddress: var_lastReadAddress,
      lastReadValue: var_lastReadValue,
      message: var_message,
    );
  }

  @protected
  HomeDashboard sse_decode_home_dashboard(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_endpoint = sse_decode_String(deserializer);
    var var_connectionStatus = sse_decode_String(deserializer);
    var var_values = sse_decode_list_home_dashboard_value(deserializer);
    var var_lastUpdated = sse_decode_String(deserializer);
    return HomeDashboard(
      endpoint: var_endpoint,
      connectionStatus: var_connectionStatus,
      values: var_values,
      lastUpdated: var_lastUpdated,
    );
  }

  @protected
  HomeDashboardValue sse_decode_home_dashboard_value(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_u_16(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_rawValue = sse_decode_u_16(deserializer);
    var var_engineeringValue = sse_decode_f_64(deserializer);
    var var_displayValue = sse_decode_String(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_quality = sse_decode_String(deserializer);
    return HomeDashboardValue(
      address: var_address,
      name: var_name,
      rawValue: var_rawValue,
      engineeringValue: var_engineeringValue,
      displayValue: var_displayValue,
      unit: var_unit,
      quality: var_quality,
    );
  }

  @protected
  ImportedSimulatorProfile sse_decode_imported_simulator_profile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_vendor = sse_decode_String(deserializer);
    var var_communicationType = sse_decode_String(deserializer);
    var var_registers = sse_decode_list_imported_simulator_register(
      deserializer,
    );
    var var_scenarios = sse_decode_list_imported_simulator_scenario(
      deserializer,
    );
    return ImportedSimulatorProfile(
      id: var_id,
      name: var_name,
      version: var_version,
      deviceType: var_deviceType,
      vendor: var_vendor,
      communicationType: var_communicationType,
      registers: var_registers,
      scenarios: var_scenarios,
    );
  }

  @protected
  ImportedSimulatorRegister sse_decode_imported_simulator_register(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_address = sse_decode_u_16(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_functionCode = sse_decode_u_8(deserializer);
    var var_access = sse_decode_String(deserializer);
    var var_dataType = sse_decode_String(deserializer);
    var var_length = sse_decode_u_16(deserializer);
    var var_scale = sse_decode_f_64(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_rangeMin = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_rangeMax = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_group = sse_decode_String(deserializer);
    var var_engineeringValue = sse_decode_f_64(deserializer);
    return ImportedSimulatorRegister(
      id: var_id,
      address: var_address,
      name: var_name,
      functionCode: var_functionCode,
      access: var_access,
      dataType: var_dataType,
      length: var_length,
      scale: var_scale,
      unit: var_unit,
      rangeMin: var_rangeMin,
      rangeMax: var_rangeMax,
      description: var_description,
      group: var_group,
      engineeringValue: var_engineeringValue,
    );
  }

  @protected
  ImportedSimulatorScenario sse_decode_imported_simulator_scenario(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_steps = sse_decode_list_imported_simulator_scenario_step(
      deserializer,
    );
    var var_faultMode = sse_decode_String(deserializer);
    var var_exceptionCode = sse_decode_u_8(deserializer);
    var var_rate = sse_decode_f_64(deserializer);
    return ImportedSimulatorScenario(
      id: var_id,
      name: var_name,
      description: var_description,
      steps: var_steps,
      faultMode: var_faultMode,
      exceptionCode: var_exceptionCode,
      rate: var_rate,
    );
  }

  @protected
  ImportedSimulatorScenarioStep sse_decode_imported_simulator_scenario_step(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_registerId = sse_decode_String(deserializer);
    var var_strategy = sse_decode_String(deserializer);
    var var_value = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_min = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_max = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_step = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_amplitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_offset = sse_decode_opt_box_autoadd_f_64(deserializer);
    return ImportedSimulatorScenarioStep(
      registerId: var_registerId,
      strategy: var_strategy,
      value: var_value,
      min: var_min,
      max: var_max,
      step: var_step,
      amplitude: var_amplitude,
      offset: var_offset,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ActivityItem> sse_decode_list_activity_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ActivityItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_activity_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceSimulatorFrame> sse_decode_list_device_simulator_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceSimulatorFrame>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_simulator_frame(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceSimulatorRegisterDefinition>
  sse_decode_list_device_simulator_register_definition(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceSimulatorRegisterDefinition>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_simulator_register_definition(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceSimulatorRegisterState>
  sse_decode_list_device_simulator_register_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceSimulatorRegisterState>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_simulator_register_state(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceSimulatorValueUpdate>
  sse_decode_list_device_simulator_value_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceSimulatorValueUpdate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_simulator_value_update(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceStatus> sse_decode_list_device_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceStatus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_status(deserializer));
    }
    return ans_;
  }

  @protected
  List<HomeDashboardValue> sse_decode_list_home_dashboard_value(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HomeDashboardValue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_home_dashboard_value(deserializer));
    }
    return ans_;
  }

  @protected
  List<ImportedSimulatorRegister> sse_decode_list_imported_simulator_register(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ImportedSimulatorRegister>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_imported_simulator_register(deserializer));
    }
    return ans_;
  }

  @protected
  List<ImportedSimulatorScenario> sse_decode_list_imported_simulator_scenario(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ImportedSimulatorScenario>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_imported_simulator_scenario(deserializer));
    }
    return ans_;
  }

  @protected
  List<ImportedSimulatorScenarioStep>
  sse_decode_list_imported_simulator_scenario_step(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ImportedSimulatorScenarioStep>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_imported_simulator_scenario_step(deserializer));
    }
    return ans_;
  }

  @protected
  List<MetricCard> sse_decode_list_metric_card(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MetricCard>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_metric_card(deserializer));
    }
    return ans_;
  }

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TrendPoint> sse_decode_list_trend_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrendPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_trend_point(deserializer));
    }
    return ans_;
  }

  @protected
  MetricCard sse_decode_metric_card(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_tone = sse_decode_String(deserializer);
    var var_helper = sse_decode_String(deserializer);
    return MetricCard(
      key: var_key,
      label: var_label,
      value: var_value,
      unit: var_unit,
      tone: var_tone,
      helper: var_helper,
    );
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  HomeDashboard? sse_decode_opt_box_autoadd_home_dashboard(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_home_dashboard(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectInfo sse_decode_project_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_protocolVersion = sse_decode_String(deserializer);
    var var_operator_ = sse_decode_String(deserializer);
    return ProjectInfo(
      name: var_name,
      protocolVersion: var_protocolVersion,
      operator_: var_operator_,
    );
  }

  @protected
  SimulatorStatus sse_decode_simulator_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_running = sse_decode_bool(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_unitId = sse_decode_u_8(deserializer);
    var var_registerCount = sse_decode_u_32(deserializer);
    var var_logs = sse_decode_list_String(deserializer);
    return SimulatorStatus(
      running: var_running,
      endpoint: var_endpoint,
      unitId: var_unitId,
      registerCount: var_registerCount,
      logs: var_logs,
    );
  }

  @protected
  TrendPoint sse_decode_trend_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_time = sse_decode_String(deserializer);
    var var_power = sse_decode_f_64(deserializer);
    var var_soc = sse_decode_f_64(deserializer);
    var var_quality = sse_decode_f_64(deserializer);
    return TrendPoint(
      time: var_time,
      power: var_power,
      soc: var_soc,
      quality: var_quality,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_activity_item(ActivityItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tone, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.detail, serializer);
    sse_encode_String(self.time, serializer);
  }

  @protected
  void sse_encode_app_snapshot(AppSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_project_info(self.project, serializer);
    sse_encode_connection_info(self.connection, serializer);
    sse_encode_list_metric_card(self.metrics, serializer);
    sse_encode_list_device_status(self.devices, serializer);
    sse_encode_list_activity_item(self.activities, serializer);
    sse_encode_list_trend_point(self.trends, serializer);
    sse_encode_opt_box_autoadd_home_dashboard(self.homeDashboard, serializer);
  }

  @protected
  void sse_encode_backend_status(BackendStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serviceName, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_bool(self.bridgeReady, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_home_dashboard(
    HomeDashboard self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_home_dashboard(self, serializer);
  }

  @protected
  void sse_encode_connection_info(
    ConnectionInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mode, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_u_16(self.latencyMs, serializer);
    sse_encode_f_64(self.successRate, serializer);
  }

  @protected
  void sse_encode_device_simulator_exception_stats(
    DeviceSimulatorExceptionStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.ok, serializer);
    sse_encode_u_32(self.exceptionCode, serializer);
    sse_encode_u_32(self.timeout, serializer);
    sse_encode_u_32(self.noResponse, serializer);
    sse_encode_u_32(self.outOfRange, serializer);
  }

  @protected
  void sse_encode_device_simulator_frame(
    DeviceSimulatorFrame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.direction, serializer);
    sse_encode_String(self.time, serializer);
    sse_encode_String(self.frame, serializer);
    sse_encode_String(self.note, serializer);
  }

  @protected
  void sse_encode_device_simulator_register_definition(
    DeviceSimulatorRegisterDefinition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.address, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.dataType, serializer);
    sse_encode_u_16(self.length, serializer);
    sse_encode_f_64(self.scale, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_f_64(self.engineeringValue, serializer);
  }

  @protected
  void sse_encode_device_simulator_register_state(
    DeviceSimulatorRegisterState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.address, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.dataType, serializer);
    sse_encode_u_16(self.length, serializer);
    sse_encode_f_64(self.scale, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_f_64(self.engineeringValue, serializer);
    sse_encode_list_prim_u_16_strict(self.rawWords, serializer);
  }

  @protected
  void sse_encode_device_simulator_status(
    DeviceSimulatorStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.running, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_u_8(self.unitId, serializer);
    sse_encode_String(self.faultMode, serializer);
    sse_encode_list_device_simulator_register_state(self.registers, serializer);
    sse_encode_list_String(self.logs, serializer);
    sse_encode_list_device_simulator_frame(self.frames, serializer);
    sse_encode_device_simulator_exception_stats(self.stats, serializer);
  }

  @protected
  void sse_encode_device_simulator_value_update(
    DeviceSimulatorValueUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.address, serializer);
    sse_encode_f_64(self.engineeringValue, serializer);
  }

  @protected
  void sse_encode_device_status(DeviceStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_String(self.connection, serializer);
    sse_encode_String(self.runtime, serializer);
    sse_encode_String(self.quality, serializer);
    sse_encode_String(self.lastSeen, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_fault_config(FaultConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mode, serializer);
    sse_encode_u_8(self.exceptionCode, serializer);
    sse_encode_f_64(self.rate, serializer);
  }

  @protected
  void sse_encode_home_connection_status(
    HomeConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.connected, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_u_8(self.unitId, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_u_32(self.latencyMs, serializer);
    sse_encode_f_64(self.successRate, serializer);
    sse_encode_u_16(self.lastReadAddress, serializer);
    sse_encode_u_16(self.lastReadValue, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_home_dashboard(HomeDashboard self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.endpoint, serializer);
    sse_encode_String(self.connectionStatus, serializer);
    sse_encode_list_home_dashboard_value(self.values, serializer);
    sse_encode_String(self.lastUpdated, serializer);
  }

  @protected
  void sse_encode_home_dashboard_value(
    HomeDashboardValue self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.address, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_16(self.rawValue, serializer);
    sse_encode_f_64(self.engineeringValue, serializer);
    sse_encode_String(self.displayValue, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_String(self.quality, serializer);
  }

  @protected
  void sse_encode_imported_simulator_profile(
    ImportedSimulatorProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_String(self.vendor, serializer);
    sse_encode_String(self.communicationType, serializer);
    sse_encode_list_imported_simulator_register(self.registers, serializer);
    sse_encode_list_imported_simulator_scenario(self.scenarios, serializer);
  }

  @protected
  void sse_encode_imported_simulator_register(
    ImportedSimulatorRegister self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_u_16(self.address, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_8(self.functionCode, serializer);
    sse_encode_String(self.access, serializer);
    sse_encode_String(self.dataType, serializer);
    sse_encode_u_16(self.length, serializer);
    sse_encode_f_64(self.scale, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_opt_box_autoadd_f_64(self.rangeMin, serializer);
    sse_encode_opt_box_autoadd_f_64(self.rangeMax, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.group, serializer);
    sse_encode_f_64(self.engineeringValue, serializer);
  }

  @protected
  void sse_encode_imported_simulator_scenario(
    ImportedSimulatorScenario self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_list_imported_simulator_scenario_step(self.steps, serializer);
    sse_encode_String(self.faultMode, serializer);
    sse_encode_u_8(self.exceptionCode, serializer);
    sse_encode_f_64(self.rate, serializer);
  }

  @protected
  void sse_encode_imported_simulator_scenario_step(
    ImportedSimulatorScenarioStep self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.registerId, serializer);
    sse_encode_String(self.strategy, serializer);
    sse_encode_opt_box_autoadd_f_64(self.value, serializer);
    sse_encode_opt_box_autoadd_f_64(self.min, serializer);
    sse_encode_opt_box_autoadd_f_64(self.max, serializer);
    sse_encode_opt_box_autoadd_f_64(self.step, serializer);
    sse_encode_opt_box_autoadd_f_64(self.amplitude, serializer);
    sse_encode_opt_box_autoadd_f_64(self.offset, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_activity_item(
    List<ActivityItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_activity_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_simulator_frame(
    List<DeviceSimulatorFrame> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_simulator_frame(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_simulator_register_definition(
    List<DeviceSimulatorRegisterDefinition> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_simulator_register_definition(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_simulator_register_state(
    List<DeviceSimulatorRegisterState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_simulator_register_state(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_simulator_value_update(
    List<DeviceSimulatorValueUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_simulator_value_update(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_status(
    List<DeviceStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_status(item, serializer);
    }
  }

  @protected
  void sse_encode_list_home_dashboard_value(
    List<HomeDashboardValue> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_home_dashboard_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_imported_simulator_register(
    List<ImportedSimulatorRegister> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_imported_simulator_register(item, serializer);
    }
  }

  @protected
  void sse_encode_list_imported_simulator_scenario(
    List<ImportedSimulatorScenario> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_imported_simulator_scenario(item, serializer);
    }
  }

  @protected
  void sse_encode_list_imported_simulator_scenario_step(
    List<ImportedSimulatorScenarioStep> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_imported_simulator_scenario_step(item, serializer);
    }
  }

  @protected
  void sse_encode_list_metric_card(
    List<MetricCard> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_metric_card(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_trend_point(
    List<TrendPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_trend_point(item, serializer);
    }
  }

  @protected
  void sse_encode_metric_card(MetricCard self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.value, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_String(self.tone, serializer);
    sse_encode_String(self.helper, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_home_dashboard(
    HomeDashboard? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_home_dashboard(self, serializer);
    }
  }

  @protected
  void sse_encode_project_info(ProjectInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.protocolVersion, serializer);
    sse_encode_String(self.operator_, serializer);
  }

  @protected
  void sse_encode_simulator_status(
    SimulatorStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.running, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_u_8(self.unitId, serializer);
    sse_encode_u_32(self.registerCount, serializer);
    sse_encode_list_String(self.logs, serializer);
  }

  @protected
  void sse_encode_trend_point(TrendPoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.time, serializer);
    sse_encode_f_64(self.power, serializer);
    sse_encode_f_64(self.soc, serializer);
    sse_encode_f_64(self.quality, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
