// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

BackendStatus getBackendStatus() =>
    RustLib.instance.api.crateApiBackendGetBackendStatus();

class BackendStatus {
  final String serviceName;
  final String version;
  final bool bridgeReady;

  const BackendStatus({
    required this.serviceName,
    required this.version,
    required this.bridgeReady,
  });

  @override
  int get hashCode =>
      serviceName.hashCode ^ version.hashCode ^ bridgeReady.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackendStatus &&
          runtimeType == other.runtimeType &&
          serviceName == other.serviceName &&
          version == other.version &&
          bridgeReady == other.bridgeReady;
}
