// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_value`, `disconnected_status`, `elapsed_ms`, `normalize_config`, `point`, `poll_dashboard`, `runtime_status`, `system_state_label`, `write_home_register`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HomeConnectionRuntime`, `PointDefinition`, `ValueKind`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

Future<HomeConnectionStatus> connectHomeModbus({
  required String host,
  required int port,
  required int unitId,
}) => RustLib.instance.api.crateApiConnectionConnectHomeModbus(
  host: host,
  port: port,
  unitId: unitId,
);

Future<HomeConnectionStatus> refreshHomeModbus() =>
    RustLib.instance.api.crateApiConnectionRefreshHomeModbus();

HomeConnectionStatus disconnectHomeModbus() =>
    RustLib.instance.api.crateApiConnectionDisconnectHomeModbus();

HomeConnectionStatus getHomeConnectionStatus() =>
    RustLib.instance.api.crateApiConnectionGetHomeConnectionStatus();

HomeDashboard getHomeDashboard() =>
    RustLib.instance.api.crateApiConnectionGetHomeDashboard();

class HomeConnectionStatus {
  final bool connected;
  final String endpoint;
  final int unitId;
  final String status;
  final int latencyMs;
  final double successRate;
  final int lastReadAddress;
  final int lastReadValue;
  final String message;

  const HomeConnectionStatus({
    required this.connected,
    required this.endpoint,
    required this.unitId,
    required this.status,
    required this.latencyMs,
    required this.successRate,
    required this.lastReadAddress,
    required this.lastReadValue,
    required this.message,
  });

  @override
  int get hashCode =>
      connected.hashCode ^
      endpoint.hashCode ^
      unitId.hashCode ^
      status.hashCode ^
      latencyMs.hashCode ^
      successRate.hashCode ^
      lastReadAddress.hashCode ^
      lastReadValue.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeConnectionStatus &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          endpoint == other.endpoint &&
          unitId == other.unitId &&
          status == other.status &&
          latencyMs == other.latencyMs &&
          successRate == other.successRate &&
          lastReadAddress == other.lastReadAddress &&
          lastReadValue == other.lastReadValue &&
          message == other.message;
}

class HomeDashboard {
  final String endpoint;
  final String connectionStatus;
  final List<HomeDashboardValue> values;
  final String lastUpdated;

  const HomeDashboard({
    required this.endpoint,
    required this.connectionStatus,
    required this.values,
    required this.lastUpdated,
  });

  @override
  int get hashCode =>
      endpoint.hashCode ^
      connectionStatus.hashCode ^
      values.hashCode ^
      lastUpdated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeDashboard &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          connectionStatus == other.connectionStatus &&
          values == other.values &&
          lastUpdated == other.lastUpdated;
}

class HomeDashboardValue {
  final int address;
  final String name;
  final int rawValue;
  final double engineeringValue;
  final String displayValue;
  final String unit;
  final String quality;

  const HomeDashboardValue({
    required this.address,
    required this.name,
    required this.rawValue,
    required this.engineeringValue,
    required this.displayValue,
    required this.unit,
    required this.quality,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      name.hashCode ^
      rawValue.hashCode ^
      engineeringValue.hashCode ^
      displayValue.hashCode ^
      unit.hashCode ^
      quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeDashboardValue &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          name == other.name &&
          rawValue == other.rawValue &&
          engineeringValue == other.engineeringValue &&
          displayValue == other.displayValue &&
          unit == other.unit &&
          quality == other.quality;
}
