// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_fault`, `build_points`, `decode_words`, `encode_words`, `exception_response`, `normalize_data_type`, `normalize_host`, `process_pdu`, `push_frame`, `push_log`, `read_word`, `request_note`, `response_frame`, `response_note`, `runtime_status`, `serve_client`, `serve`, `set_point_value`, `stopped_status`, `unix_seconds`, `with_runtime`, `write_word`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DeviceSimulatorRuntime`, `PointDataType`, `SharedState`, `SimulatorPoint`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<DeviceSimulatorStatus> startDeviceSimulator({
  required String host,
  required int port,
  required int unitId,
  required List<DeviceSimulatorRegisterDefinition> registers,
}) => RustLib.instance.api.crateApiDeviceSimulatorStartDeviceSimulator(
  host: host,
  port: port,
  unitId: unitId,
  registers: registers,
);

DeviceSimulatorStatus stopDeviceSimulator() =>
    RustLib.instance.api.crateApiDeviceSimulatorStopDeviceSimulator();

DeviceSimulatorStatus getDeviceSimulatorStatus() =>
    RustLib.instance.api.crateApiDeviceSimulatorGetDeviceSimulatorStatus();

DeviceSimulatorStatus setDeviceSimulatorRegister({
  required int address,
  required double engineeringValue,
}) => RustLib.instance.api.crateApiDeviceSimulatorSetDeviceSimulatorRegister(
  address: address,
  engineeringValue: engineeringValue,
);

DeviceSimulatorStatus applyDeviceSimulatorValues({
  required List<DeviceSimulatorValueUpdate> updates,
}) => RustLib.instance.api.crateApiDeviceSimulatorApplyDeviceSimulatorValues(
  updates: updates,
);

DeviceSimulatorStatus setDeviceSimulatorFault({
  required String mode,
  required int exceptionCode,
  required double rate,
}) => RustLib.instance.api.crateApiDeviceSimulatorSetDeviceSimulatorFault(
  mode: mode,
  exceptionCode: exceptionCode,
  rate: rate,
);

class DeviceSimulatorExceptionStats {
  final int ok;
  final int exceptionCode;
  final int timeout;
  final int noResponse;
  final int outOfRange;

  const DeviceSimulatorExceptionStats({
    required this.ok,
    required this.exceptionCode,
    required this.timeout,
    required this.noResponse,
    required this.outOfRange,
  });

  static Future<DeviceSimulatorExceptionStats> default_() => RustLib
      .instance
      .api
      .crateApiDeviceSimulatorDeviceSimulatorExceptionStatsDefault();

  @override
  int get hashCode =>
      ok.hashCode ^
      exceptionCode.hashCode ^
      timeout.hashCode ^
      noResponse.hashCode ^
      outOfRange.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSimulatorExceptionStats &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          exceptionCode == other.exceptionCode &&
          timeout == other.timeout &&
          noResponse == other.noResponse &&
          outOfRange == other.outOfRange;
}

class DeviceSimulatorFrame {
  final String direction;
  final String time;
  final String frame;
  final String note;

  const DeviceSimulatorFrame({
    required this.direction,
    required this.time,
    required this.frame,
    required this.note,
  });

  @override
  int get hashCode =>
      direction.hashCode ^ time.hashCode ^ frame.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSimulatorFrame &&
          runtimeType == other.runtimeType &&
          direction == other.direction &&
          time == other.time &&
          frame == other.frame &&
          note == other.note;
}

class DeviceSimulatorRegisterDefinition {
  final int address;
  final String name;
  final String dataType;
  final int length;
  final double scale;
  final String unit;
  final double engineeringValue;

  const DeviceSimulatorRegisterDefinition({
    required this.address,
    required this.name,
    required this.dataType,
    required this.length,
    required this.scale,
    required this.unit,
    required this.engineeringValue,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      name.hashCode ^
      dataType.hashCode ^
      length.hashCode ^
      scale.hashCode ^
      unit.hashCode ^
      engineeringValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSimulatorRegisterDefinition &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          name == other.name &&
          dataType == other.dataType &&
          length == other.length &&
          scale == other.scale &&
          unit == other.unit &&
          engineeringValue == other.engineeringValue;
}

class DeviceSimulatorRegisterState {
  final int address;
  final String name;
  final String dataType;
  final int length;
  final double scale;
  final String unit;
  final double engineeringValue;
  final Uint16List rawWords;

  const DeviceSimulatorRegisterState({
    required this.address,
    required this.name,
    required this.dataType,
    required this.length,
    required this.scale,
    required this.unit,
    required this.engineeringValue,
    required this.rawWords,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      name.hashCode ^
      dataType.hashCode ^
      length.hashCode ^
      scale.hashCode ^
      unit.hashCode ^
      engineeringValue.hashCode ^
      rawWords.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSimulatorRegisterState &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          name == other.name &&
          dataType == other.dataType &&
          length == other.length &&
          scale == other.scale &&
          unit == other.unit &&
          engineeringValue == other.engineeringValue &&
          rawWords == other.rawWords;
}

class DeviceSimulatorStatus {
  final bool running;
  final String endpoint;
  final int unitId;
  final String faultMode;
  final List<DeviceSimulatorRegisterState> registers;
  final List<String> logs;
  final List<DeviceSimulatorFrame> frames;
  final DeviceSimulatorExceptionStats stats;

  const DeviceSimulatorStatus({
    required this.running,
    required this.endpoint,
    required this.unitId,
    required this.faultMode,
    required this.registers,
    required this.logs,
    required this.frames,
    required this.stats,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      endpoint.hashCode ^
      unitId.hashCode ^
      faultMode.hashCode ^
      registers.hashCode ^
      logs.hashCode ^
      frames.hashCode ^
      stats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSimulatorStatus &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          endpoint == other.endpoint &&
          unitId == other.unitId &&
          faultMode == other.faultMode &&
          registers == other.registers &&
          logs == other.logs &&
          frames == other.frames &&
          stats == other.stats;
}

class DeviceSimulatorValueUpdate {
  final int address;
  final double engineeringValue;

  const DeviceSimulatorValueUpdate({
    required this.address,
    required this.engineeringValue,
  });

  @override
  int get hashCode => address.hashCode ^ engineeringValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSimulatorValueUpdate &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          engineeringValue == other.engineeringValue;
}

class FaultConfig {
  final String mode;
  final int exceptionCode;
  final double rate;

  const FaultConfig({
    required this.mode,
    required this.exceptionCode,
    required this.rate,
  });

  static Future<FaultConfig> default_() =>
      RustLib.instance.api.crateApiDeviceSimulatorFaultConfigDefault();

  @override
  int get hashCode => mode.hashCode ^ exceptionCode.hashCode ^ rate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FaultConfig &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          exceptionCode == other.exceptionCode &&
          rate == other.rate;
}
