// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `aliases`, `cell_text`, `expected_length`, `generic_scenarios`, `json_number`, `json_string`, `mapped_value`, `nonempty`, `nonzero`, `normalize_access`, `normalize_data_type`, `normalize_header`, `parse_csv`, `parse_json`, `parse_number`, `parse_range`, `parse_workbook`, `profile_from_rows`, `register_from_json`, `register_from_row`, `scenario_from_json`, `scenario`, `slug`, `table_rows`, `value_as_number`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ImportedSimulatorProfile> importDeviceSimulatorProfile({
  required String path,
}) => RustLib.instance.api.crateApiProfileImportImportDeviceSimulatorProfile(
  path: path,
);

class ImportedSimulatorProfile {
  final String id;
  final String name;
  final String version;
  final String deviceType;
  final String vendor;
  final String communicationType;
  final List<ImportedSimulatorRegister> registers;
  final List<ImportedSimulatorScenario> scenarios;

  const ImportedSimulatorProfile({
    required this.id,
    required this.name,
    required this.version,
    required this.deviceType,
    required this.vendor,
    required this.communicationType,
    required this.registers,
    required this.scenarios,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      version.hashCode ^
      deviceType.hashCode ^
      vendor.hashCode ^
      communicationType.hashCode ^
      registers.hashCode ^
      scenarios.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportedSimulatorProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          version == other.version &&
          deviceType == other.deviceType &&
          vendor == other.vendor &&
          communicationType == other.communicationType &&
          registers == other.registers &&
          scenarios == other.scenarios;
}

class ImportedSimulatorRegister {
  final String id;
  final int address;
  final String name;
  final int functionCode;
  final String access;
  final String dataType;
  final int length;
  final double scale;
  final String unit;
  final double? rangeMin;
  final double? rangeMax;
  final String description;
  final String group;
  final double engineeringValue;

  const ImportedSimulatorRegister({
    required this.id,
    required this.address,
    required this.name,
    required this.functionCode,
    required this.access,
    required this.dataType,
    required this.length,
    required this.scale,
    required this.unit,
    this.rangeMin,
    this.rangeMax,
    required this.description,
    required this.group,
    required this.engineeringValue,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      address.hashCode ^
      name.hashCode ^
      functionCode.hashCode ^
      access.hashCode ^
      dataType.hashCode ^
      length.hashCode ^
      scale.hashCode ^
      unit.hashCode ^
      rangeMin.hashCode ^
      rangeMax.hashCode ^
      description.hashCode ^
      group.hashCode ^
      engineeringValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportedSimulatorRegister &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          address == other.address &&
          name == other.name &&
          functionCode == other.functionCode &&
          access == other.access &&
          dataType == other.dataType &&
          length == other.length &&
          scale == other.scale &&
          unit == other.unit &&
          rangeMin == other.rangeMin &&
          rangeMax == other.rangeMax &&
          description == other.description &&
          group == other.group &&
          engineeringValue == other.engineeringValue;
}

class ImportedSimulatorScenario {
  final String id;
  final String name;
  final String description;
  final List<ImportedSimulatorScenarioStep> steps;
  final String faultMode;
  final int exceptionCode;
  final double rate;

  const ImportedSimulatorScenario({
    required this.id,
    required this.name,
    required this.description,
    required this.steps,
    required this.faultMode,
    required this.exceptionCode,
    required this.rate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      steps.hashCode ^
      faultMode.hashCode ^
      exceptionCode.hashCode ^
      rate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportedSimulatorScenario &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          steps == other.steps &&
          faultMode == other.faultMode &&
          exceptionCode == other.exceptionCode &&
          rate == other.rate;
}

class ImportedSimulatorScenarioStep {
  final String registerId;
  final String strategy;
  final double? value;
  final double? min;
  final double? max;
  final double? step;
  final double? amplitude;
  final double? offset;

  const ImportedSimulatorScenarioStep({
    required this.registerId,
    required this.strategy,
    this.value,
    this.min,
    this.max,
    this.step,
    this.amplitude,
    this.offset,
  });

  @override
  int get hashCode =>
      registerId.hashCode ^
      strategy.hashCode ^
      value.hashCode ^
      min.hashCode ^
      max.hashCode ^
      step.hashCode ^
      amplitude.hashCode ^
      offset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportedSimulatorScenarioStep &&
          runtimeType == other.runtimeType &&
          registerId == other.registerId &&
          strategy == other.strategy &&
          value == other.value &&
          min == other.min &&
          max == other.max &&
          step == other.step &&
          amplitude == other.amplitude &&
          offset == other.offset;
}
