// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'connection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_home_self_test_status_result`, `handle_request`, `normalize_local_host`, `push_log`, `seed_registers`, `serve_client`, `serve`, `stopped_status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SimulatorRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

Future<HomeConnectionStatus> startHomeSelfTest({
  required String host,
  required int port,
  required int unitId,
}) => RustLib.instance.api.crateApiSimulatorStartHomeSelfTest(
  host: host,
  port: port,
  unitId: unitId,
);

SimulatorStatus setHomeSelfTestRegister({
  required int address,
  required int rawValue,
}) => RustLib.instance.api.crateApiSimulatorSetHomeSelfTestRegister(
  address: address,
  rawValue: rawValue,
);

SimulatorStatus stopHomeSelfTest() =>
    RustLib.instance.api.crateApiSimulatorStopHomeSelfTest();

SimulatorStatus getHomeSelfTestStatus() =>
    RustLib.instance.api.crateApiSimulatorGetHomeSelfTestStatus();

class SimulatorStatus {
  final bool running;
  final String endpoint;
  final int unitId;
  final int registerCount;
  final List<String> logs;

  const SimulatorStatus({
    required this.running,
    required this.endpoint,
    required this.unitId,
    required this.registerCount,
    required this.logs,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      endpoint.hashCode ^
      unitId.hashCode ^
      registerCount.hashCode ^
      logs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatorStatus &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          endpoint == other.endpoint &&
          unitId == other.unitId &&
          registerCount == other.registerCount &&
          logs == other.logs;
}
