// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'connection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dashboard_engineering_value`, `dashboard_value`, `metric`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

AppSnapshot getAppSnapshot() =>
    RustLib.instance.api.crateApiSnapshotGetAppSnapshot();

class ActivityItem {
  final String tone;
  final String title;
  final String detail;
  final String time;

  const ActivityItem({
    required this.tone,
    required this.title,
    required this.detail,
    required this.time,
  });

  @override
  int get hashCode =>
      tone.hashCode ^ title.hashCode ^ detail.hashCode ^ time.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActivityItem &&
          runtimeType == other.runtimeType &&
          tone == other.tone &&
          title == other.title &&
          detail == other.detail &&
          time == other.time;
}

class AppSnapshot {
  final ProjectInfo project;
  final ConnectionInfo connection;
  final List<MetricCard> metrics;
  final List<DeviceStatus> devices;
  final List<ActivityItem> activities;
  final List<TrendPoint> trends;
  final HomeDashboard? homeDashboard;

  const AppSnapshot({
    required this.project,
    required this.connection,
    required this.metrics,
    required this.devices,
    required this.activities,
    required this.trends,
    this.homeDashboard,
  });

  @override
  int get hashCode =>
      project.hashCode ^
      connection.hashCode ^
      metrics.hashCode ^
      devices.hashCode ^
      activities.hashCode ^
      trends.hashCode ^
      homeDashboard.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSnapshot &&
          runtimeType == other.runtimeType &&
          project == other.project &&
          connection == other.connection &&
          metrics == other.metrics &&
          devices == other.devices &&
          activities == other.activities &&
          trends == other.trends &&
          homeDashboard == other.homeDashboard;
}

class ConnectionInfo {
  final String mode;
  final String endpoint;
  final String status;
  final int latencyMs;
  final double successRate;

  const ConnectionInfo({
    required this.mode,
    required this.endpoint,
    required this.status,
    required this.latencyMs,
    required this.successRate,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      endpoint.hashCode ^
      status.hashCode ^
      latencyMs.hashCode ^
      successRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionInfo &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          endpoint == other.endpoint &&
          status == other.status &&
          latencyMs == other.latencyMs &&
          successRate == other.successRate;
}

class DeviceStatus {
  final String name;
  final String deviceType;
  final String connection;
  final String runtime;
  final String quality;
  final String lastSeen;

  const DeviceStatus({
    required this.name,
    required this.deviceType,
    required this.connection,
    required this.runtime,
    required this.quality,
    required this.lastSeen,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      deviceType.hashCode ^
      connection.hashCode ^
      runtime.hashCode ^
      quality.hashCode ^
      lastSeen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceStatus &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          deviceType == other.deviceType &&
          connection == other.connection &&
          runtime == other.runtime &&
          quality == other.quality &&
          lastSeen == other.lastSeen;
}

class MetricCard {
  final String key;
  final String label;
  final String value;
  final String unit;
  final String tone;
  final String helper;

  const MetricCard({
    required this.key,
    required this.label,
    required this.value,
    required this.unit,
    required this.tone,
    required this.helper,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      value.hashCode ^
      unit.hashCode ^
      tone.hashCode ^
      helper.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetricCard &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          value == other.value &&
          unit == other.unit &&
          tone == other.tone &&
          helper == other.helper;
}

class ProjectInfo {
  final String name;
  final String protocolVersion;
  final String operator_;

  const ProjectInfo({
    required this.name,
    required this.protocolVersion,
    required this.operator_,
  });

  @override
  int get hashCode =>
      name.hashCode ^ protocolVersion.hashCode ^ operator_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          protocolVersion == other.protocolVersion &&
          operator_ == other.operator_;
}

class TrendPoint {
  final String time;
  final double power;
  final double soc;
  final double quality;

  const TrendPoint({
    required this.time,
    required this.power,
    required this.soc,
    required this.quality,
  });

  @override
  int get hashCode =>
      time.hashCode ^ power.hashCode ^ soc.hashCode ^ quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrendPoint &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          power == other.power &&
          soc == other.soc &&
          quality == other.quality;
}
